apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
spec:
  selector:
    app: sistema-lanchonete
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
